PARTS = ['body/8+9/', 'body/NO8+9/', 'expression/8+9/', 'expression/NO8+9/', 'hair/8+9/', 'hair/NO8+9/', 'eye/8+9/', 'eye/NO8+9/', 'hand/8+9/', 'hand/NO8+9/']
SPECIAL_PARTS = ['special edition/body/', 'special edition/hand/']
HEIGHT = 1415
WIDTH = 1280
NUM_DISTRIB = 500
SEARCH_DIR = "./image/"
INPUT_IMGTYPE = '.png'
OUTPUT_IMGTYPE = '.png'
OUTPUT_PATH = './result/final/'
PROJ_NAME = 'BAKAJOHN#'
TRANSPARENT_PATH = './image/special edition/hand/'